In [34]:
import torch

width = 4
height = 4
pose = torch.eye(4)
focal = 1

ii, jj = torch.meshgrid(torch.arange(width).to(pose), torch.arange(height).to(pose), indexing='ij')
ii.transpose_(-1, -2)
jj.transpose_(-1, -2)
directions = torch.stack([(ii - width * .5) / focal, -(jj - height * .5) / focal, -torch.ones_like(ii)], dim=-1)

In [35]:
print(ii)
print(jj)

tensor([[0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.]])
tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])


In [36]:
directions

tensor([[[-2.,  2., -1.],
         [-1.,  2., -1.],
         [ 0.,  2., -1.],
         [ 1.,  2., -1.]],

        [[-2.,  1., -1.],
         [-1.,  1., -1.],
         [ 0.,  1., -1.],
         [ 1.,  1., -1.]],

        [[-2., -0., -1.],
         [-1., -0., -1.],
         [ 0., -0., -1.],
         [ 1., -0., -1.]],

        [[-2., -1., -1.],
         [-1., -1., -1.],
         [ 0., -1., -1.],
         [ 1., -1., -1.]]])

In [38]:
directions[..., None, :]

tensor([[[[-2.,  2., -1.]],

         [[-1.,  2., -1.]],

         [[ 0.,  2., -1.]],

         [[ 1.,  2., -1.]]],


        [[[-2.,  1., -1.]],

         [[-1.,  1., -1.]],

         [[ 0.,  1., -1.]],

         [[ 1.,  1., -1.]]],


        [[[-2., -0., -1.]],

         [[-1., -0., -1.]],

         [[ 0., -0., -1.]],

         [[ 1., -0., -1.]]],


        [[[-2., -1., -1.]],

         [[-1., -1., -1.]],

         [[ 0., -1., -1.]],

         [[ 1., -1., -1.]]]])

In [39]:
directions = torch.randn(2, 2, 3)
print(directions.shape)  # 输出: torch.Size([2, 2, 3])

# 使用 `None` 插入新维度
directions_expanded = directions[..., None, :]
print(directions_expanded.shape)  # 输出: torch.Size([2, 2, 1, 3])

torch.Size([2, 2, 3])
torch.Size([2, 2, 1, 3])
